### PR TITLE
Fix console output encoding

### PR DESCRIPTION
**Pull request by jairbubbles**
It fixes the issue as the output encoding in the plugin seems to be "windows-1252".

### CODE REVIEW

**Comment by liamkf** [comment]
Cool! I don't suppose you gave it a try with the Console.OutputEncoding? I figure if someone is in Russian or some East Asian language we may as well try to get it in the right encoding for them too! :)

**Comment by jairbubbles** [comment]
Nope it doesn't work. Console.OutpoutEncoding returns windows 1252.

**Comment by jairbubbles** [comment]
But yes I agree that it's not pretty.

When looking at .net code, the function calls the native function:
**GetConsoleOutputCP**
Retrieves the output code page used by the console associated with the calling process
(https://msdn.microsoft.com/en-us/library/windows/desktop/ms683169(v=vs.85).aspx)

So I guess the console CP associated with visual studio plugins is not the default one (there is a setconsoleCP function).

What we would need is a function that returns the default code page for console or even better the code page associated with the msfastbuild.exe process. But I don't understand why it's not the default behavior.

**Comment by jairbubbles** [comment]
It's quite complex but this returns 850:

```
[System.Runtime.InteropServices.DllImport("kernel32.dll")]
public static extern int GetSystemDefaultLCID();

int lcid = GetSystemDefaultLCID();
var ci = System.Globalization.CultureInfo.GetCultureInfo(lcid);
var page = ci.TextInfo.OEMCodePage;
```

**Comment by liamkf** [comment]
Ok I've gone the GetSystemDefaultLCID route... ugly as it is. :)

**Pull request closed without merging**
